service: codebit-labs-fo-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    labs: "true"
    project: codebit-labs
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: codebit-labs-fo-api-serverless
  stage: ${opt:stage, 'dev'}

custom:
  serverless-layers:
    - common:
      packageManager: yarn
      dependenciesPath: ./../package.json
    - api:
      functions:
        - api
      packageManager: yarn
      dependenciesPath: ./package.json
  webpack:
    packages: yarn
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  api:
    handler: src/handler.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      DATABASE_LOGGING: ${file(./.env.${self:provider.stage}.json):general.database.logging}
      DATABASE_USERNAME: ${file(./.env.${self:provider.stage}.json):general.database.username}
      DATABASE_PASSWORD: ${file(./.env.${self:provider.stage}.json):general.database.password}
      DATABASE_HOST: ${file(./.env.${self:provider.stage}.json):general.database.host}
      DATABASE_PORT: ${file(./.env.${self:provider.stage}.json):general.database.port}
      DATABASE_NAME: ${file(./.env.${self:provider.stage}.json):general.database.name}
      DATABASE_CONNECT_TIMEOUT: ${file(./.env.${self:provider.stage}.json):general.database.connectTimeout}
      DATABASE_TIMEZONE: ${file(./.env.${self:provider.stage}.json):general.database.timezone}
      DATABASE_PREFIX: ${file(./.env.${self:provider.stage}.json):general.database.prefix}
resources:
  - ${file(./infrastructure/network.yml)}
  - ${file(./infrastructure/rds.yml)}
