service: codebit-labs-fo-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  tags:
    labs: "true"
    project: codebit-labs
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: codebit-labs-fo-api-serverless
  stage: ${opt:stage, 'dev'}

custom:
  serverless-layers:
    - common:
      packageManager: yarn
      dependenciesPath: ./../package.json
    - api:
      functions:
        - api
      packageManager: yarn
      dependenciesPath: ./package.json
  webpack:
    packages: yarn
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  api:
    handler: src/handler.api
    #    The following are a few example events you can configure
    #    NOTE: Please make sure to change your handler code to work with those events
    #    Check the event documentation for details
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
resources:
  - ${file(./infrastructure/network.yml)}
  - ${file(./infrastructure/rds.yml)}
